# I. Data Coding and Merging

In [1]:
# Load packages
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Load game logs data
Teams = pd.read_excel("Game logs 1999-2003.xlsx")

In [3]:
# Dummy variables for home and away wins
Teams['hwin'] = np.where(Teams['home_score'] > Teams['visitor_score'],1,0)
Teams['awin'] = np.where(Teams['home_score'] < Teams['visitor_score'],1,0)

In [4]:
# Extract year from date
Teams['year'] = Teams['date'].astype(str).str[0:4]
display(Teams)

,date,game_number,day,visitor,visitor_lg,visitor_game_number,home,home_lg,home_game_number,visitor_score,...,home_batter_8_name,home_batter_8_pos,home_batter_9_id,home_batter_9_name,home_batter_9_pos,additional_info,acquisition,hwin,awin,year
0,19990404,0,Sun,COL,NL,1,SDN,NL,1,8,...,Chris Gomez,6,ashba002,Andy Ashby,1,NaN,Y,0,1,1999
1,19990405,0,Mon,TBA,AL,1,BAL,AL,1,7,...,Charles Johnson,2,reboj001,Jeff Reboulet,4,NaN,Y,1,0,1999
2,19990405,0,Mon,BOS,AL,1,KCA,AL,1,5,...,Rey Sanchez,6,feblc001,Carlos Febles,4,NaN,Y,0,1,1999
3,19990405,0,Mon,NYA,AL,1,OAK,AL,1,3,...,A.J. Hinch,2,tejam001,Miguel Tejada,6,NaN,Y,1,0,1999
4,19990405,0,Mon,CHA,AL,1,SEA,AL,1,8,...,Russ Davis,5,wilsd001,Dan Wilson,2,NaN,Y,0,1,1999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12137,20030928,0,Sun,NYN,NL,161,FLO,NL,162,0,...,Mike Redmond,2,willd003,Dontrelle Willis,1,NaN,Y,1,0,2003
12138,20030928,0,Sun,MIL,NL,162,HOU,NL,162,5,...,Adam Everett,6,saark001,Kirk Saarloos,1,NaN,Y,1,0,2003
12139,20030928,0,Sun,ATL,NL,162,PHI,NL,162,5,...,Tomas Perez,5,millk004,Kevin Millwood,1,NaN,Y,0,1,2003
12140,20030928,0,Sun,COL,NL,162,SDN,NL,162,10,...,Gary Bennett,2,peavj001,Jake Peavy,1,NaN,Y,0,1,2003
12141,20030928,0,Sun,LAN,NL,162,SFN,NL,161,3,...,Yorvit Torrealba,2,corrk001,Kevin Correia,1,NaN,Y,1,0,2003

In [5]:
# Aggregate stats for home team
Teamshome = Teams.groupby(['home','year'])['visitor_ab', 'visitor_h', 'visitor_2b', 'visitor_3b', 'visitor_hr', 'visitor_sf',
                                           'visitor_hbp','visitor_bb','home_ab', 'home_h', 'home_2b', 'home_3b',
                                           'home_hr', 'home_sf', 'home_hbp', 'home_bb', 'hwin','awin'].sum()
Teamshome = Teamshome.reset_index()
Teamshome = Teamshome.rename(columns = {"home": "Team"}) 
Teamshome

/tmp/ipykernel_6473/2076997730.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  Teamshome = Teams.groupby(['home','year'])['visitor_ab', 'visitor_h', 'visitor_2b', 'visitor_3b', 'visitor_hr', 'visitor_sf',

,Team,year,visitor_ab,visitor_h,visitor_2b,visitor_3b,visitor_hr,visitor_sf,visitor_hbp,visitor_bb,home_ab,home_h,home_2b,home_3b,home_hr,home_sf,home_hbp,home_bb,hwin,awin
0,ANA,1999,2832,762,151,10,105,39,27,322,2666,669,118,13,74,21,23,267,37,44
1,ANA,2000,2867,800,144,8,113,24,15,320,2742,788,146,11,130,23,24,315,46,35
2,ANA,2001,2873,772,165,6,86,20,39,259,2736,731,122,12,86,29,30,251,39,42
3,ANA,2002,2799,685,132,5,70,29,22,260,2757,769,155,21,71,27,34,228,54,27
4,ANA,2003,2868,743,142,9,84,17,39,245,2685,717,135,17,68,22,27,226,45,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,TOR,1999,2891,817,190,11,93,31,25,289,2731,765,173,6,96,21,44,283,40,41
146,TOR,2000,2910,819,182,11,92,19,30,279,2766,768,178,9,134,12,33,255,45,36
147,TOR,2001,2911,800,207,17,84,25,46,264,2809,757,146,14,94,31,37,256,40,42
148,TOR,2002,2838,749,171,10,89,28,37,288,2729,734,164,20,102,24,30,258,42,39
149,TOR,2003,2930,827,172,19,107,20,33,244,2763,779,191,16,94,28,40,284,41,40

In [6]:
# Aggregate stats for away team
Teamsaway = Teams.groupby(['year','visitor'])['visitor_ab', 'visitor_h', 'visitor_2b', 'visitor_3b', 
                                           'visitor_hr', 'visitor_sf', 'visitor_hbp', 'visitor_bb', 
                                           'home_ab', 'home_h', 'home_2b', 'home_3b', 'home_hr', 
                                           'home_sf', 'home_hbp', 'home_bb','hwin','awin'].sum()

Teamsaway = Teamsaway.reset_index()
Teamsaway = Teamsaway.rename(columns = {"visitor": "Team"}) 
Teamsaway

/tmp/ipykernel_6473/196108921.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  Teamsaway = Teams.groupby(['year','visitor'])['visitor_ab', 'visitor_h', 'visitor_2b', 'visitor_3b',

,year,Team,visitor_ab,visitor_h,visitor_2b,visitor_3b,visitor_hr,visitor_sf,visitor_hbp,visitor_bb,home_ab,home_h,home_2b,home_3b,home_hr,home_sf,home_hbp,home_bb,hwin,awin
0,1999,ANA,2828,735,130,9,84,21,20,244,2645,710,134,15,72,26,29,302,48,33
1,1999,ARI,2928,812,147,15,115,29,31,303,2751,694,123,12,92,14,22,287,33,48
2,1999,ATL,2901,777,151,14,111,19,31,322,2772,724,131,9,67,22,16,286,34,47
3,1999,BAL,2905,810,163,12,105,23,25,300,2638,708,157,19,97,22,19,318,44,37
4,1999,BOS,2857,758,157,22,96,27,25,292,2704,674,134,10,88,23,23,243,36,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,2003,SFN,2752,689,147,10,98,18,26,287,2590,657,124,12,75,26,23,285,37,43
146,2003,SLN,2914,781,159,21,111,30,34,300,2831,815,180,16,117,27,37,276,44,37
147,2003,TBA,2859,749,140,17,81,29,27,188,2663,719,163,17,100,30,32,317,54,27
148,2003,TEX,2877,708,133,13,99,15,41,242,2719,770,154,17,103,34,24,319,53,28
149,2003,TOR,2898,801,166,17,96,28,50,262,2730,733,128,23,77,18,24,241,36,45

In [7]:
# Merge into one dataframe
Teams2 = pd.merge(Teamshome, Teamsaway, on =['Team','year'])
pd.set_option('display.max_columns', 50)
display(Teams2)

,Team,year,visitor_ab_x,visitor_h_x,visitor_2b_x,visitor_3b_x,visitor_hr_x,visitor_sf_x,visitor_hbp_x,visitor_bb_x,home_ab_x,home_h_x,home_2b_x,home_3b_x,home_hr_x,home_sf_x,home_hbp_x,home_bb_x,hwin_x,awin_x,visitor_ab_y,visitor_h_y,visitor_2b_y,visitor_3b_y,visitor_hr_y,visitor_sf_y,visitor_hbp_y,visitor_bb_y,home_ab_y,home_h_y,home_2b_y,home_3b_y,home_hr_y,home_sf_y,home_hbp_y,home_bb_y,hwin_y,awin_y
0,ANA,1999,2832,762,151,10,105,39,27,322,2666,669,118,13,74,21,23,267,37,44,2828,735,130,9,84,21,20,244,2645,710,134,15,72,26,29,302,48,33
1,ANA,2000,2867,800,144,8,113,24,15,320,2742,788,146,11,130,23,24,315,46,35,2886,786,163,23,106,20,23,293,2742,734,132,15,115,29,21,342,45,36
2,ANA,2001,2873,772,165,6,86,20,39,259,2736,731,122,12,86,29,30,251,39,42,2815,716,153,14,72,24,47,243,2656,680,120,13,82,19,25,266,45,36
3,ANA,2002,2799,685,132,5,70,29,22,260,2757,769,155,21,71,27,34,228,54,27,2921,834,178,11,81,37,40,234,2654,660,116,14,99,30,27,249,36,45
4,ANA,2003,2868,743,142,9,84,17,39,245,2685,717,135,17,68,22,27,226,45,37,2802,756,141,16,82,28,29,250,2664,701,118,18,106,25,37,241,48,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,TOR,1999,2891,817,190,11,93,31,25,289,2731,765,173,6,96,21,44,283,40,41,2911,815,164,8,116,24,32,295,2753,765,135,22,98,26,28,286,37,44
146,TOR,2000,2910,819,182,11,92,19,30,279,2766,768,178,9,134,12,33,255,45,36,2911,794,150,12,110,22,27,271,2759,796,156,12,103,21,34,281,43,38
147,TOR,2001,2911,800,207,17,84,25,46,264,2809,757,146,14,94,31,37,256,40,42,2854,732,141,22,101,12,37,214,2738,753,150,9,81,18,30,226,40,40
148,TOR,2002,2838,749,171,10,89,28,37,288,2729,734,164,20,102,24,30,258,42,39,2852,723,141,18,85,33,23,264,2745,755,141,19,88,24,34,302,45,36
149,TOR,2003,2930,827,172,19,107,20,33,244,2763,779,191,16,94,28,40,284,41,40,2898,801,166,17,96,28,50,262,2730,733,128,23,77,18,24,241,36,45

In [8]:
# Total Wins
Teams2['wins'] = Teams2['hwin_x']+Teams2['awin_y']

In [9]:
MedWins = Teams2.groupby(['year'])['wins'].median()
MedWins

year
1999    77.5
2000    82.0
2001    82.0
2002    79.5
2003    84.5
Name: wins, dtype: float64

In [10]:
# Home hits
HomeHits = Teamshome.groupby(['year'])['home_h'].min()
HomeHits

year
1999    669
2000    634
2001    614
2002    636
2003    619
Name: home_h, dtype: int64

In [11]:
# Avg AB
AwayAB = Teamsaway.groupby(['year'])['visitor_ab'].mean()
AwayAB

year
1999    2852.066667
2000    2855.333333
2001    2834.466667
2002    2823.200000
2003    2844.933333
Name: visitor_ab, dtype: float64

# II. Calculating Performance Metrics

In [12]:
# Create batting average for and batting average against
Teams2['AVGFOR'] = (Teams2['home_h_x'] + Teams2['visitor_h_y'])/(Teams2['home_ab_x'] + Teams2['visitor_ab_y'])
Teams2['AVGAGN'] = (Teams2['home_h_y'] + Teams2['visitor_h_x'])/(Teams2['home_ab_y'] + Teams2['visitor_ab_x'])

In [13]:
# Calculate win percentage
Teams3 = Teams2[['year', 'Team', 'wins','AVGFOR','AVGAGN']]

TeamsGh = Teams.groupby(['year','home'])['hwin'].count()
TeamsGh = TeamsGh.reset_index()
TeamsGh = TeamsGh.rename(columns = {"home": 'Team', "hwin": 'hgame'}) 

TeamsGa = Teams.groupby(['year','visitor'])['awin'].count()
TeamsGa = TeamsGa.reset_index()
TeamsGa = TeamsGa.rename(columns = {"visitor": 'Team', "awin": 'agame'}) 

TeamsG = pd.merge(TeamsGh, TeamsGa, on =['Team','year'])
TeamsG['Games'] = TeamsG['hgame']+TeamsG['agame']
TeamsG = TeamsG[['year','Team','Games']]

Teams3 = pd.merge(Teams3, TeamsG, on =['Team','year'])
Teams3['wpc'] = Teams3['wins']/Teams3['Games']
Teams3

     year Team  wins    AVGFOR    AVGAGN  Games       wpc
0    1999  ANA    70  0.255552  0.268760    162  0.432099
1    2000  ANA    82  0.279673  0.273489    162  0.506173
2    2001  ANA    75  0.260674  0.262615    162  0.462963
3    2002  ANA    99  0.282318  0.246653    162  0.611111
4    2003  ANA    77  0.268453  0.261027    162  0.475309
..    ...  ...   ...       ...       ...    ...       ...
145  1999  TOR    84  0.280043  0.280298    162  0.518519
146  2000  TOR    83  0.275145  0.284883    162  0.512346
147  2001  TOR    80  0.262935  0.274916    162  0.493827
148  2002  TOR    78  0.261064  0.269389    162  0.481481
149  2003  TOR    86  0.279103  0.275618    162  0.530864

[150 rows x 7 columns]

In [14]:
# Calculate home win percentage and away win percentage
TeamsWh = Teams.groupby(['year','home'])['hwin'].sum()
TeamsWh = TeamsWh.reset_index()
TeamsWh = TeamsWh.rename(columns = {"home": 'Team'}) 
Teamsh = pd.merge(TeamsGh, TeamsWh, on=['Team','year'])
Teamsh['hwpc'] = Teamsh['hwin']/Teamsh['hgame']
Teamsh

     year Team  hgame  hwin      hwpc
0    1999  ANA     81    37  0.456790
1    1999  ARI     81    52  0.641975
2    1999  ATL     81    56  0.691358
3    1999  BAL     81    41  0.506173
4    1999  BOS     81    49  0.604938
..    ...  ...    ...   ...       ...
145  2003  SFN     81    57  0.703704
146  2003  SLN     81    48  0.592593
147  2003  TBA     81    36  0.444444
148  2003  TEX     81    43  0.530864
149  2003  TOR     81    41  0.506173

[150 rows x 5 columns]

In [15]:
TeamsWa = Teams.groupby(['year','visitor'])['awin'].sum()
TeamsWa = TeamsWa.reset_index()
TeamsWa = TeamsWa.rename(columns = {"visitor": 'Team'})
Teamsa = pd.merge(TeamsGa, TeamsWa, on=['Team','year'])
Teamsa['awpc'] = Teamsa['awin']/Teamsa['agame']
Teamsa

     year Team  agame  awin      awpc
0    1999  ANA     81    33  0.407407
1    1999  ARI     81    48  0.592593
2    1999  ATL     81    47  0.580247
3    1999  BAL     81    37  0.456790
4    1999  BOS     81    45  0.555556
..    ...  ...    ...   ...       ...
145  2003  SFN     80    43  0.537500
146  2003  SLN     81    37  0.456790
147  2003  TBA     81    27  0.333333
148  2003  TEX     81    28  0.345679
149  2003  TOR     81    45  0.555556

[150 rows x 5 columns]

In [16]:
# Merge home and away win percentage data frames and calculate difference
Teamsha = pd.merge(Teamsh, Teamsa, on=['Team','year'])
Teamsha['wpc_diff'] = Teamsha['hwpc'] - Teamsha['awpc']
Teamsha

     year Team  hgame  hwin      hwpc  agame  awin      awpc  wpc_diff
0    1999  ANA     81    37  0.456790     81    33  0.407407  0.049383
1    1999  ARI     81    52  0.641975     81    48  0.592593  0.049383
2    1999  ATL     81    56  0.691358     81    47  0.580247  0.111111
3    1999  BAL     81    41  0.506173     81    37  0.456790  0.049383
4    1999  BOS     81    49  0.604938     81    45  0.555556  0.049383
..    ...  ...    ...   ...       ...    ...   ...       ...       ...
145  2003  SFN     81    57  0.703704     80    43  0.537500  0.166204
146  2003  SLN     81    48  0.592593     81    37  0.456790  0.135802
147  2003  TBA     81    36  0.444444     81    27  0.333333  0.111111
148  2003  TEX     81    43  0.530864     81    28  0.345679  0.185185
149  2003  TOR     81    41  0.506173     81    45  0.555556 -0.049383

[150 rows x 9 columns]

In [17]:
# Maximum WPCT diff
Teamsha.sort_values(by=['wpc_diff'], ascending = False)

     year Team  hgame  hwin      hwpc  agame  awin      awpc  wpc_diff
129  2003  COL     81    49  0.604938     81    25  0.308642  0.296296
99   2002  COL     81    47  0.580247     81    26  0.320988  0.259259
137  2003  MON     81    52  0.641975     81    31  0.382716  0.259259
140  2003  OAK     81    57  0.703704     81    39  0.481481  0.222222
23   1999  SDN     81    46  0.567901     81    28  0.345679  0.222222
..    ...  ...    ...   ...       ...    ...   ...       ...       ...
62   2001  ATL     81    40  0.493827     81    48  0.592593 -0.098765
83   2001  SDN     81    35  0.432099     81    44  0.543210 -0.111111
94   2002  BOS     81    42  0.518519     81    51  0.629630 -0.111111
15   1999  MIL     80    32  0.400000     81    42  0.518519 -0.118519
67   2001  CIN     81    27  0.333333     81    39  0.481481 -0.148148

[150 rows x 9 columns]

In [18]:
# AVG Diff
Teams3['AVGDIFF'] = Teams3['AVGFOR'] - Teams3['AVGAGN']
Teams3.sort_values(by=['AVGDIFF'])

     year Team  wins    AVGFOR    AVGAGN  Games       wpc   AVGDIFF
54   2003  DET    43  0.240029  0.285714    162  0.265432 -0.045685
53   2002  DET    55  0.247873  0.284820    161  0.341615 -0.036948
39   2003  CIN    69  0.244872  0.278209    162  0.425926 -0.033337
30   1999  CHN    67  0.257388  0.286144    162  0.413580 -0.028756
52   2001  DET    66  0.259888  0.288506    162  0.407407 -0.028618
..    ...  ...   ...       ...       ...    ...       ...       ...
5    1999  ARI   100  0.276776  0.249236    162  0.617284  0.027540
35   1999  CIN    96  0.271907  0.241335    163  0.588957  0.030572
23   2002  BOS    93  0.276596  0.245553    162  0.574074  0.031043
3    2002  ANA    99  0.282318  0.246653    162  0.611111  0.035664
122  2001  SEA   116  0.288204  0.235519    162  0.716049  0.052685

[150 rows x 8 columns]

In [18]:
TeamsPMG = Teams3[Teams3['Games'] != 162]
TeamsPMG['Games'].count()

28