In [1]:
# First we load the packages
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# I. Building the Dataset: Player Stats

In [2]:
# Read in salary data retrieved from Lahman's Database
Salary = pd.read_csv("Salaries.csv")

# Read in batting
Batting = pd.read_csv("Batting.csv")

Load the “Salaries” file, drop any missing values, create a variable for the natural log (ln) of player salary, and rename the column “yearID” as “SalYear”.

In [3]:
#drop missing values

Salary = Salary[Salary.salary >0]
Salary

       yearID teamID lgID   playerID    salary
0        1985    ATL   NL  barkele01    870000
1        1985    ATL   NL  bedrost01    550000
2        1985    ATL   NL  benedbr01    545000
3        1985    ATL   NL   campri01    633333
4        1985    ATL   NL  ceronri01    625000
...       ...    ...  ...        ...       ...
26423    2016    WAS   NL  strasst01  10400000
26424    2016    WAS   NL  taylomi02    524000
26425    2016    WAS   NL  treinbl01    524900
26426    2016    WAS   NL  werthja01  21733615
26427    2016    WAS   NL  zimmery01  14000000

[26426 rows x 5 columns]

In [4]:
Salary['lnSal'] = np.log(Salary.salary)
Salary

       yearID teamID lgID   playerID    salary      lnSal
0        1985    ATL   NL  barkele01    870000  13.676248
1        1985    ATL   NL  bedrost01    550000  13.217674
2        1985    ATL   NL  benedbr01    545000  13.208541
3        1985    ATL   NL   campri01    633333  13.358752
4        1985    ATL   NL  ceronri01    625000  13.345507
...       ...    ...  ...        ...       ...        ...
26423    2016    WAS   NL  strasst01  10400000  16.157316
26424    2016    WAS   NL  taylomi02    524000  13.169247
26425    2016    WAS   NL  treinbl01    524900  13.170963
26426    2016    WAS   NL  werthja01  21733615  16.894371
26427    2016    WAS   NL  zimmery01  14000000  16.454568

[26426 rows x 6 columns]

In [5]:
Salary = Salary.rename(columns = {'yearID':'SalYear'})
Salary

       SalYear teamID lgID   playerID    salary      lnSal
0         1985    ATL   NL  barkele01    870000  13.676248
1         1985    ATL   NL  bedrost01    550000  13.217674
2         1985    ATL   NL  benedbr01    545000  13.208541
3         1985    ATL   NL   campri01    633333  13.358752
4         1985    ATL   NL  ceronri01    625000  13.345507
...        ...    ...  ...        ...       ...        ...
26423     2016    WAS   NL  strasst01  10400000  16.157316
26424     2016    WAS   NL  taylomi02    524000  13.169247
26425     2016    WAS   NL  treinbl01    524900  13.170963
26426     2016    WAS   NL  werthja01  21733615  16.894371
26427     2016    WAS   NL  zimmery01  14000000  16.454568

[26426 rows x 6 columns]

In [6]:
Master = Salary
Master

       SalYear teamID lgID   playerID    salary      lnSal
0         1985    ATL   NL  barkele01    870000  13.676248
1         1985    ATL   NL  bedrost01    550000  13.217674
2         1985    ATL   NL  benedbr01    545000  13.208541
3         1985    ATL   NL   campri01    633333  13.358752
4         1985    ATL   NL  ceronri01    625000  13.345507
...        ...    ...  ...        ...       ...        ...
26423     2016    WAS   NL  strasst01  10400000  16.157316
26424     2016    WAS   NL  taylomi02    524000  13.169247
26425     2016    WAS   NL  treinbl01    524900  13.170963
26426     2016    WAS   NL  werthja01  21733615  16.894371
26427     2016    WAS   NL  zimmery01  14000000  16.454568

[26426 rows x 6 columns]

In [7]:
# Load the batting data and sum across stints
Batting = pd.read_csv('Batting.csv')
pd.set_option('display.max_columns', 50)
display(Batting)

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,abercda01,1871,1,TRO,NaN,1,4,0,0,0,0,0,0.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
1,addybo01,1871,1,RC1,NaN,25,118,30,32,6,0,0,13.0,8.0,1.0,4,0.0,NaN,NaN,NaN,NaN,NaN
2,allisar01,1871,1,CL1,NaN,29,137,28,40,4,5,0,19.0,3.0,1.0,2,5.0,NaN,NaN,NaN,NaN,NaN
3,allisdo01,1871,1,WS3,NaN,27,133,28,44,10,2,2,27.0,1.0,1.0,0,2.0,NaN,NaN,NaN,NaN,NaN
4,ansonca01,1871,1,RC1,NaN,25,120,29,39,11,3,0,16.0,6.0,2.0,2,1.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102811,zimmejo02,2016,1,DET,AL,19,4,0,1,0,0,0,0.0,0.0,0.0,0,2.0,0.0,0.0,1.0,0.0,0.0
102812,zimmery01,2016,1,WAS,NL,115,427,60,93,18,1,15,46.0,4.0,1.0,29,104.0,1.0,5.0,0.0,6.0,12.0
102813,zobribe01,2016,1,CHN,NL,147,523,94,142,31,3,18,76.0,6.0,4.0,96,82.0,6.0,4.0,4.0,4.0,17.0
102814,zuninmi01,2016,1,SEA,AL,55,164,16,34,7,0,12,31.0,0.0,0.0,21,65.0,0.0,6.0,0.0,1.0,0.0
102815,zychto01,2016,1,SEA,AL,12,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
#Stints

Batting = Batting.groupby(['playerID', 'yearID']).sum()
Batting.reset_index(inplace=True)
Batting

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,aardsda01,2004,1,11,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,aardsda01,2006,1,45,2,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0
2,aardsda01,2007,1,25,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,aardsda01,2008,1,47,1,0,0,0,0,0,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
4,aardsda01,2009,1,73,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95245,zwilldu01,1914,1,154,592,91,185,38,8,16,95.0,21.0,0.0,46,68.0,0.0,1.0,10.0,0.0,0.0
95246,zwilldu01,1915,1,150,548,65,157,32,7,13,94.0,24.0,0.0,67,65.0,0.0,2.0,18.0,0.0,0.0
95247,zwilldu01,1916,1,35,53,4,6,1,0,1,8.0,0.0,0.0,4,6.0,0.0,0.0,2.0,0.0,0.0
95248,zychto01,2015,1,13,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
95249,zychto01,2016,1,12,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
Batting = Batting[(Batting.yearID >= 1998) & \
                  (Batting.yearID <= 2006) & \
                  (Batting.AB >= 130)].copy()
Batting

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
98,abbotje01,1998,1,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0
100,abbotje01,2000,1,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0
117,abbotku01,1998,3,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0
118,abbotku01,1999,1,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0
119,abbotku01,2000,1,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94988,zeileto01,2002,1,144,506,61,138,23,0,18,87.0,1.0,1.0,66,92.0,3.0,1.0,0.0,7.0,27.0
94989,zeileto01,2003,3,100,299,40,68,10,2,11,42.0,1.0,0.0,34,54.0,0.0,3.0,0.0,5.0,6.0
94990,zeileto01,2004,1,137,348,30,81,16,0,9,35.0,0.0,0.0,44,83.0,1.0,1.0,1.0,2.0,13.0
95105,zimmery01,2006,1,157,614,84,176,47,3,20,110.0,11.0,8.0,61,120.0,7.0,2.0,1.0,4.0,15.0
95170,zobribe01,2006,1,52,183,10,41,6,2,2,18.0,2.0,3.0,10,26.0,1.0,0.0,2.0,3.0,2.0

In [10]:
Batting['PA'] = Batting.AB + \
                Batting.BB + \
                Batting.HBP + \
                Batting.SH + \
                Batting.SF

In [11]:
Batting['OBP'] = (Batting.H + 
                  Batting.BB + 
                  Batting.HBP) / (Batting.AB + 
                                 Batting.BB + 
                                 Batting.HBP + 
                                 Batting.SF)

In [12]:
Batting['SLG'] = ((Batting.H - 
                   Batting.Doubles - 
                   Batting.Triples -  
                   Batting.HR) + 
                  2 * Batting.Doubles + 
                  3 * Batting.Triples + 
                  4 * Batting.HR) / Batting.AB

In [13]:
Batting['AVG'] = Batting.H / Batting.AB

In [14]:
Batting

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,AVG
98,abbotje01,1998,1,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,0.278689
100,abbotje01,2000,1,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,0.274419
117,abbotku01,1998,3,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,0.262887
118,abbotku01,1999,1,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0,305.0,0.310231,0.430070,0.272727
119,abbotku01,2000,1,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0,173.0,0.283237,0.388535,0.216561
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94988,zeileto01,2002,1,144,506,61,138,23,0,18,87.0,1.0,1.0,66,92.0,3.0,1.0,0.0,7.0,27.0,580.0,0.353448,0.424901,0.272727
94989,zeileto01,2003,3,100,299,40,68,10,2,11,42.0,1.0,0.0,34,54.0,0.0,3.0,0.0,5.0,6.0,341.0,0.307918,0.384615,0.227425
94990,zeileto01,2004,1,137,348,30,81,16,0,9,35.0,0.0,0.0,44,83.0,1.0,1.0,1.0,2.0,13.0,396.0,0.318987,0.356322,0.232759
95105,zimmery01,2006,1,157,614,84,176,47,3,20,110.0,11.0,8.0,61,120.0,7.0,2.0,1.0,4.0,15.0,682.0,0.350954,0.470684,0.286645
95170,zobribe01,2006,1,52,183,10,41,6,2,2,18.0,2.0,3.0,10,26.0,1.0,0.0,2.0,3.0,2.0,198.0,0.260204,0.311475,0.224044

In [15]:
Batting['SalYear'] = Batting.yearID + 1
Batting

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,AVG,SalYear
98,abbotje01,1998,1,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,0.278689,1999
100,abbotje01,2000,1,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,0.274419,2001
117,abbotku01,1998,3,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,0.262887,1999
118,abbotku01,1999,1,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0,305.0,0.310231,0.430070,0.272727,2000
119,abbotku01,2000,1,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0,173.0,0.283237,0.388535,0.216561,2001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94988,zeileto01,2002,1,144,506,61,138,23,0,18,87.0,1.0,1.0,66,92.0,3.0,1.0,0.0,7.0,27.0,580.0,0.353448,0.424901,0.272727,2003
94989,zeileto01,2003,3,100,299,40,68,10,2,11,42.0,1.0,0.0,34,54.0,0.0,3.0,0.0,5.0,6.0,341.0,0.307918,0.384615,0.227425,2004
94990,zeileto01,2004,1,137,348,30,81,16,0,9,35.0,0.0,0.0,44,83.0,1.0,1.0,1.0,2.0,13.0,396.0,0.318987,0.356322,0.232759,2005
95105,zimmery01,2006,1,157,614,84,176,47,3,20,110.0,11.0,8.0,61,120.0,7.0,2.0,1.0,4.0,15.0,682.0,0.350954,0.470684,0.286645,2007
95170,zobribe01,2006,1,52,183,10,41,6,2,2,18.0,2.0,3.0,10,26.0,1.0,0.0,2.0,3.0,2.0,198.0,0.260204,0.311475,0.224044,2007

In [16]:
Master = pd.merge(Batting, Master, on=['SalYear','playerID'])
Master

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,AVG,SalYear,teamID,lgID,salary,lnSal
0,abbotje01,1998,1,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,0.278689,1999,CHA,AL,255000,12.449019
1,abbotje01,2000,1,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,0.274419,2001,FLO,NL,300000,12.611538
2,abbotku01,1998,3,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,0.262887,1999,COL,NL,900000,13.710150
3,abbotku01,1999,1,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0,305.0,0.310231,0.430070,0.272727,2000,NYN,NL,500000,13.122363
4,abbotku01,2000,1,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0,173.0,0.283237,0.388535,0.216561,2001,ATL,NL,600000,13.304685
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3109,zeileto01,2000,1,153,544,67,146,36,3,22,79.0,3.0,4.0,74,85.0,4.0,2.0,0.0,3.0,15.0,623.0,0.356340,0.466912,0.268382,2001,NYN,NL,6833333,15.737323
3110,zeileto01,2001,1,151,531,66,141,25,1,10,62.0,1.0,0.0,73,102.0,3.0,6.0,0.0,2.0,15.0,612.0,0.359477,0.372881,0.265537,2002,COL,NL,6833333,15.737323
3111,zeileto01,2002,1,144,506,61,138,23,0,18,87.0,1.0,1.0,66,92.0,3.0,1.0,0.0,7.0,27.0,580.0,0.353448,0.424901,0.272727,2003,NYA,AL,1500000,14.220976
3112,zeileto01,2003,3,100,299,40,68,10,2,11,42.0,1.0,0.0,34,54.0,0.0,3.0,0.0,5.0,6.0,341.0,0.307918,0.384615,0.227425,2004,NYN,NL,1000000,13.815511
3113,zobribe01,2006,1,52,183,10,41,6,2,2,18.0,2.0,3.0,10,26.0,1.0,0.0,2.0,3.0,2.0,198.0,0.260204,0.311475,0.224044,2007,TBA,AL,383400,12.856834

In [17]:
# Question 1
# What was the average player salary in 1999?  
# What was the average player salary in 2006?

# sal99 = Master[Master.SalYear == 1999]
# print(sal99.salary.mean(),'\n')
# sal99
# sal06 = Master[Master.SalYear == 2006]
# print(sal06.salary.mean(), '\n')
# sal06
MeanSal = Master.groupby(['SalYear'])['salary'].mean().reset_index()
MeanSal

   SalYear        salary
0     1999  2.223975e+06
1     2000  2.590626e+06
2     2001  3.029559e+06
3     2002  3.153773e+06
4     2003  3.472972e+06
5     2004  3.322968e+06
6     2005  3.575228e+06
7     2006  3.689305e+06
8     2007  3.942908e+06

In [18]:
# Question 2
# Calculate the average player OBP and SLG for every season in the timeframe.  
szns = Master.yearID.unique()
# szns.sort()
print(szns)

[1998 2000 1999 2001 2002 2003 2004 2005 2006]

def find_mean_per_season(szn, idx_col, stat_col, df=Master):
    sznstat = df[df[idx_col] == szn]
    stat = sznstat[stat_col].mean()
    return stat, szn

for szn in szns:
    print('\nOBP')
    a, b = find_mean_per_season(szn, 'yearID', 'OBP')
    print(a, b)
    print('\nSLG')
    c, d = find_mean_per_season(szn, 'yearID', 'SLG')
    print(c, d)
    print('-----------------------')
# Which season had the highest average player OBP and what was its value?  
# Which season had the highest average player SLG and what was its value?

In [19]:
#Calculate average player OBP and SLG
Mean_OBPSLG = Master.groupby(['yearID'])[['OBP','SLG']].mean()
display(Mean_OBPSLG)
max_OBP = max(Mean_OBPSLG['OBP'])
display(max_OBP)
max_SLG = max(Mean_OBPSLG['SLG'])
display(max_SLG)

             OBP       SLG
yearID
1998    0.337745  0.423344
1999    0.349470  0.442120
2000    0.348212  0.443840
2001    0.335789  0.433420
2002    0.335490  0.426230
2003    0.337403  0.430938
2004    0.341663  0.440307
2005    0.335947  0.428867
2006    0.342937  0.443275

0.3494702314348347

0.4438399312443786

In [20]:
# Question 3
# Sum HR by player across the entire timeframe.  
# What was the highest aggregate home run total over the timeframe 1998-2006?       

#HomeRuns = Master.groupby('playerID').sum()
#HomeRuns.sort_values('HR', ascending=False).head(20)

HR_Timeframe = Master.groupby(['playerID'])[['HR','RBI']].sum().reset_index()
HR_Timeframe = HR_Timeframe.sort_values(by=['HR'], ascending=False)
display(HR_Timeframe)

      playerID   HR     RBI
630  rodrial01  400  1119.0
679   sosasa01  367   888.0
608  ramirma02  361  1144.0
78   bondsba01  355   826.0
181  delgaca01  340  1069.0
..         ...  ...     ...
355  husonje01    0    18.0
722  tynerja01    0    39.0
597   posesc01    0    12.0
250  gathrjo01    0    13.0
692  strando01    0    14.0

[786 rows x 3 columns]

# II. Building the Dataset: Player Info

In [21]:
# Read in People data retrieved from Lahman's Database
People = pd.read_csv("People.csv")

In [22]:
Debut = People[['playerID','debut']].copy()
Debut.head()

    playerID       debut
0  aardsda01  2004-04-06
1  aaronha01  1954-04-13
2  aaronto01  1962-04-10
3   aasedo01  1977-07-26
4   abadan01  2001-09-10

In [23]:
Debut['debutyr'] = Debut.debut.astype(str).str[:4]
Debut.head()

    playerID       debut debutyr
0  aardsda01  2004-04-06    2004
1  aaronha01  1954-04-13    1954
2  aaronto01  1962-04-10    1962
3   aasedo01  1977-07-26    1977
4   abadan01  2001-09-10    2001

In [24]:
Debut = Debut[['playerID','debutyr']]
Debut.head()

    playerID debutyr
0  aardsda01    2004
1  aaronha01    1954
2  aaronto01    1962
3   aasedo01    1977
4   abadan01    2001

In [25]:
Master = pd.merge(Master, Debut, 
                  on = ['playerID'],  how = 'left')
Master.head()

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,AVG,SalYear,teamID,lgID,salary,lnSal,debutyr
0,abbotje01,1998,1,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,0.278689,1999,CHA,AL,255000,12.449019,1997
1,abbotje01,2000,1,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,0.274419,2001,FLO,NL,300000,12.611538,1997
2,abbotku01,1998,3,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,0.262887,1999,COL,NL,900000,13.710150,1993
3,abbotku01,1999,1,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0,305.0,0.310231,0.430070,0.272727,2000,NYN,NL,500000,13.122363,1993
4,abbotku01,2000,1,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0,173.0,0.283237,0.388535,0.216561,2001,ATL,NL,600000,13.304685,1993

In [26]:
Master['Exp'] = Master.yearID - \
                Master.debutyr.astype(int)
Master.head(3)

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,AVG,SalYear,teamID,lgID,salary,lnSal,debutyr,Exp
0,abbotje01,1998,1,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,0.278689,1999,CHA,AL,255000,12.449019,1997,1
1,abbotje01,2000,1,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,0.274419,2001,FLO,NL,300000,12.611538,1997,3
2,abbotku01,1998,3,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,0.262887,1999,COL,NL,900000,13.710150,1993,5

In [27]:
Master['Arb'] = np.where((Master.Exp <= 6) &
                         (Master.Exp >= 3), 1,0)
Master['Free'] = np.where(Master.Exp > 6, 1, 0)
Master.head(3)

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,AVG,SalYear,teamID,lgID,salary,lnSal,debutyr,Exp,Arb,Free
0,abbotje01,1998,1,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,0.278689,1999,CHA,AL,255000,12.449019,1997,1,0,0
1,abbotje01,2000,1,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,0.274419,2001,FLO,NL,300000,12.611538,1997,3,1,0
2,abbotku01,1998,3,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,0.262887,1999,COL,NL,900000,13.710150,1993,5,1,0

In [28]:
Appearances = pd.read_csv("Appearances.csv")
Appearances.head(3)

,yearID,teamID,lgID,playerID,G_all,GS,G_batting,G_defense,G_p,G_c,G_1b,G_2b,G_3b,G_ss,G_lf,G_cf,G_rf,G_of,G_dh,G_ph,G_pr
0,1871,TRO,NaN,abercda01,1,1.0,1,1.0,0,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0
1,1871,RC1,NaN,addybo01,25,25.0,25,25.0,0,0,0,22,0,3,0,0,0,0,0.0,0.0,0.0
2,1871,CL1,NaN,allisar01,29,29.0,29,29.0,0,0,0,2,0,0,0,29,0,29,0.0,0.0,0.0

In [29]:
Appearances = Appearances.groupby(['playerID', 'yearID'])[['G_c','G_1b',\
                                                          'G_2b', 'G_3b', \
                                                          'G_ss', 'G_of', \
                                                          'G_dh']].sum()
Appearances.reset_index(inplace=True)
Appearances.head(3)

    playerID  yearID  G_c  G_1b  G_2b  G_3b  G_ss  G_of  G_dh
0  aardsda01    2004    0     0     0     0     0     0   0.0
1  aardsda01    2006    0     0     0     0     0     0   0.0
2  aardsda01    2007    0     0     0     0     0     0   0.0

In [30]:
Appearances['Max_G'] = Appearances[['G_c', 'G_1b', 'G_2b', \
                                    'G_3b', 'G_ss', 'G_of', \
                                    'G_dh']].max(axis=1)
Appearances.head(3)

    playerID  yearID  G_c  G_1b  G_2b  G_3b  G_ss  G_of  G_dh  Max_G
0  aardsda01    2004    0     0     0     0     0     0   0.0    0.0
1  aardsda01    2006    0     0     0     0     0     0   0.0    0.0
2  aardsda01    2007    0     0     0     0     0     0   0.0    0.0

In [31]:
pd.set_option('display.max_rows', 50)
def Position(df):
    if (df['Max_G'] == df['G_c']): return 'C'
    elif (df['Max_G'] == df['G_1b']): return '1B'
    elif (df['Max_G'] == df['G_2b']): return '2B'
    elif (df['Max_G'] == df['G_3b']): return '3B'
    elif (df['Max_G'] == df['G_ss']): return 'SS'
    elif (df['Max_G'] == df['G_of']): return 'OF'
    elif (df['Max_G'] == df['G_dh']): return 'DH'

Appearances['POS'] = Appearances.apply(Position, axis=1)
display(Appearances)

        playerID  yearID  G_c  G_1b  G_2b  G_3b  G_ss  G_of  G_dh  Max_G POS
0      aardsda01    2004    0     0     0     0     0     0   0.0    0.0   C
1      aardsda01    2006    0     0     0     0     0     0   0.0    0.0   C
2      aardsda01    2007    0     0     0     0     0     0   0.0    0.0   C
3      aardsda01    2008    0     0     0     0     0     0   0.0    0.0   C
4      aardsda01    2009    0     0     0     0     0     0   0.0    0.0   C
...          ...     ...  ...   ...   ...   ...   ...   ...   ...    ...  ..
96607  zwilldu01    1915    0     3     0     0     0   148   0.0  148.0  OF
96608  zwilldu01    1916    0     0     0     0     0     9   0.0    9.0  OF
96609   zychto01    2015    0     0     0     0     0     0   0.0    0.0   C
96610   zychto01    2016    0     0     0     0     0     0   0.0    0.0   C
96611   zychto01    2017    0     0     0     0     0     0   0.0    0.0   C

[96612 rows x 11 columns]

In [32]:
Appearances = Appearances[Appearances.Max_G > 0]
Appearances = Appearances[['playerID', 'yearID', 'POS']]
Appearances

        playerID  yearID POS
9      aaronha01    1954  OF
10     aaronha01    1955  OF
11     aaronha01    1956  OF
12     aaronha01    1957  OF
13     aaronha01    1958  OF
...          ...     ...  ..
96596  zuvelpa01    1991  3B
96605  zwilldu01    1910  OF
96606  zwilldu01    1914  OF
96607  zwilldu01    1915  OF
96608  zwilldu01    1916  OF

[55969 rows x 3 columns]

In [33]:
Appearances['Catch'] = np.where(Appearances.POS == 'C', 1, 0)
Appearances['Infld'] = np.where((Appearances.POS == '2B') | 
                                (Appearances.POS == '3B') |
                                (Appearances.POS == 'SS'), 1, 0)
Appearances

        playerID  yearID POS  Catch  Infld
9      aaronha01    1954  OF      0      0
10     aaronha01    1955  OF      0      0
11     aaronha01    1956  OF      0      0
12     aaronha01    1957  OF      0      0
13     aaronha01    1958  OF      0      0
...          ...     ...  ..    ...    ...
96596  zuvelpa01    1991  3B      0      1
96605  zwilldu01    1910  OF      0      0
96606  zwilldu01    1914  OF      0      0
96607  zwilldu01    1915  OF      0      0
96608  zwilldu01    1916  OF      0      0

[55969 rows x 5 columns]

In [34]:
Master = pd.merge(Master, Appearances, on=['playerID', 'yearID'], how = 'left')
Master

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,AVG,SalYear,teamID,lgID,salary,lnSal,debutyr,Exp,Arb,Free,POS,Catch,Infld
0,abbotje01,1998,1,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,0.278689,1999,CHA,AL,255000,12.449019,1997,1,0,0,OF,0,0
1,abbotje01,2000,1,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,0.274419,2001,FLO,NL,300000,12.611538,1997,3,1,0,OF,0,0
2,abbotku01,1998,3,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,0.262887,1999,COL,NL,900000,13.710150,1993,5,1,0,SS,0,1
3,abbotku01,1999,1,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0,305.0,0.310231,0.430070,0.272727,2000,NYN,NL,500000,13.122363,1993,6,1,0,2B,0,1
4,abbotku01,2000,1,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0,173.0,0.283237,0.388535,0.216561,2001,ATL,NL,600000,13.304685,1993,7,0,1,SS,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3109,zeileto01,2000,1,153,544,67,146,36,3,22,79.0,3.0,4.0,74,85.0,4.0,2.0,0.0,3.0,15.0,623.0,0.356340,0.466912,0.268382,2001,NYN,NL,6833333,15.737323,1989,11,0,1,1B,0,0
3110,zeileto01,2001,1,151,531,66,141,25,1,10,62.0,1.0,0.0,73,102.0,3.0,6.0,0.0,2.0,15.0,612.0,0.359477,0.372881,0.265537,2002,COL,NL,6833333,15.737323,1989,12,0,1,1B,0,0
3111,zeileto01,2002,1,144,506,61,138,23,0,18,87.0,1.0,1.0,66,92.0,3.0,1.0,0.0,7.0,27.0,580.0,0.353448,0.424901,0.272727,2003,NYA,AL,1500000,14.220976,1989,13,0,1,3B,0,1
3112,zeileto01,2003,3,100,299,40,68,10,2,11,42.0,1.0,0.0,34,54.0,0.0,3.0,0.0,5.0,6.0,341.0,0.307918,0.384615,0.227425,2004,NYN,NL,1000000,13.815511,1989,14,0,1,3B,0,1
3113,zobribe01,2006,1,52,183,10,41,6,2,2,18.0,2.0,3.0,10,26.0,1.0,0.0,2.0,3.0,2.0,198.0,0.260204,0.311475,0.224044,2007,TBA,AL,383400,12.856834,2006,0,0,0,SS,0,1

In [35]:
pd.options.display.float_format = '{:.2f}'.format
MeanSal = Master.groupby(['SalYear','POS'])['salary'].mean().reset_index()
Sal99 = MeanSal[MeanSal.SalYear == 1999]
print(Sal99)
Sal04 = MeanSal[MeanSal.SalYear == 2004]
print(Sal04)

   SalYear POS     salary
0     1999  1B 3014788.46
1     1999  2B 1847791.05
2     1999  3B 2431312.50
3     1999   C 1309344.77
4     1999  DH 3214642.86
5     1999  OF 2393860.51
6     1999  SS 1915313.92
    SalYear POS     salary
35     2004  1B 4211004.41
36     2004  2B 2056156.10
37     2004  3B 2429080.71
38     2004   C 2471140.10
39     2004  DH 3167862.50
40     2004  OF 4067222.74
41     2004  SS 3367722.22

In [36]:
Arb = Master.Arb.sum()
Free = Master.Free.sum()
#Master.shape
(Arb + Free) / Master.shape[0]

0.7880539499036608

In [37]:
Season02 = Master[Master.yearID == 2002]
Season02.groupby('teamID')['Exp'].sum()

teamID
ANA     63
ARI    107
ATL    101
BAL     49
BOS     71
CHA     69
CHN    105
CIN     50
CLE     66
COL     70
DET     37
FLO     62
HOU     99
KCA     60
LAN     70
MIL     57
MIN     47
MON     44
NYA     86
NYN     81
OAK     58
PHI     57
PIT     77
SDN     63
SEA    110
SFN    114
SLN     99
TBA     36
TEX     94
TOR     62
Name: Exp, dtype: int64

# III. Running Regressions

In [38]:
MB_Data_pre = Master[(Master.SalYear >= 1999) & (Master.SalYear <= 2003)]

In [39]:
print(Master.columns.tolist())

['playerID', 'yearID', 'stint', 'G', 'AB', 'R', 'H', 'Doubles', 'Triples', 'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'IBB', 'HBP', 'SH', 'SF', 'GIDP', 'PA', 'OBP', 'SLG', 'AVG', 'SalYear', 'teamID', 'lgID', 'salary', 'lnSal', 'debutyr', 'Exp', 'Arb', 'Free', 'POS', 'Catch', 'Infld']

In [40]:
import statsmodels.formula.api as smf

In [44]:
reg_form = 'lnSal ~ OBP + SLG + AVG + PA +Arb + Free + Catch + Infld' 
Val_All_lm_pre = smf.ols(formula = reg_form,
                         data = MB_Data_pre).fit()
Val_All_lm_pre.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  lnSal   R-squared:                       0.691
Model:                            OLS   Adj. R-squared:                  0.689
Method:                 Least Squares   F-statistic:                     486.6
Date:                Tue, 28 Dec 2021   Prob (F-statistic):               0.00
Time:                        17:09:00   Log-Likelihood:                -1858.3
No. Observations:                1753   AIC:                             3735.
Df Residuals:                    1744   BIC:                             3784.
Df Model:                           8
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     10.3702      0.164     63.101      0.000      10.048      10.693
OBP            1.4281      0.702      2.035      0.042       0.052       2.805
SLG            2.9637      0.314      9.446      0.000       2.348       3.579
AVG           -2.1911      0.886     -2.472      0.014      -3.929      -0.453
PA             0.0031      0.000     27.456      0.000       0.003       0.003
Arb            1.2487      0.046     26.879      0.000       1.158       1.340
Free           1.8202      0.046     39.163      0.000       1.729       1.911
Catch          0.1156      0.054      2.155      0.031       0.010       0.221
Infld          0.0084      0.039      0.215      0.830      -0.068       0.085
==============================================================================
Omnibus:                       11.924   Durbin-Watson:                   1.404
Prob(Omnibus):                  0.003   Jarque-Bera (JB):               16.814
Skew:                          -0.022   Prob(JB):                     0.000223
Kurtosis:                       3.478   Cond. No.                     2.90e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.9e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [45]:
MB_Data_MB = Master[(Master.SalYear >= 2004) & (Master.SalYear <= 2006)]
Val_All_lm_MB = smf.ols(formula = reg_form,
                         data = MB_Data_MB).fit()
Val_All_lm_MB.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  lnSal   R-squared:                       0.624
Model:                            OLS   Adj. R-squared:                  0.621
Method:                 Least Squares   F-statistic:                     209.2
Date:                Tue, 28 Dec 2021   Prob (F-statistic):          3.03e-208
Time:                        17:12:02   Log-Likelihood:                -1175.3
No. Observations:                1018   AIC:                             2369.
Df Residuals:                    1009   BIC:                             2413.
Df Model:                           8
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     10.0510      0.262     38.349      0.000       9.537      10.565
OBP            5.4004      1.079      5.005      0.000       3.283       7.518
SLG            2.9324      0.473      6.195      0.000       2.004       3.861
AVG           -4.7271      1.331     -3.552      0.000      -7.339      -2.116
PA             0.0030      0.000     17.650      0.000       0.003       0.003
Arb            1.0976      0.068     16.130      0.000       0.964       1.231
Free           1.6842      0.066     25.648      0.000       1.555       1.813
Catch          0.0947      0.078      1.218      0.224      -0.058       0.247
Infld         -0.0277      0.056     -0.492      0.623      -0.138       0.083
==============================================================================
Omnibus:                       12.279   Durbin-Watson:                   1.388
Prob(Omnibus):                  0.002   Jarque-Bera (JB):               15.726
Skew:                           0.151   Prob(JB):                     0.000385
Kurtosis:                       3.529   Cond. No.                     3.07e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.07e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [57]:
years = Master.SalYear.unique()
df_list = ['MB_Data_'+str(yr) for yr in years]
reg_list = ['Val_'+str(yr)+'_lm' for yr in years]
df_dict = dict(zip(years, df_list))
reg_dict = dict(zip(years, reg_list))
df_dict
reg_dict

{1999: 'Val_1999_lm',
 2001: 'Val_2001_lm',
 2000: 'Val_2000_lm',
 2002: 'Val_2002_lm',
 2003: 'Val_2003_lm',
 2004: 'Val_2004_lm',
 2005: 'Val_2005_lm',
 2006: 'Val_2006_lm',
 2007: 'Val_2007_lm'}

In [58]:
regression_list = []
for yr in years:
    df_dict[yr] = Master[(Master.SalYear == yr)]
    reg_dict[yr] = smf.ols(formula=reg_form,
                           data=df_dict[yr]).fit()
    regression_list.append(reg_dict[yr])

In [62]:
regression_list[-1].summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  lnSal   R-squared:                       0.654
Model:                            OLS   Adj. R-squared:                  0.646
Method:                 Least Squares   F-statistic:                     78.95
Date:                Tue, 28 Dec 2021   Prob (F-statistic):           2.30e-72
Time:                        17:33:55   Log-Likelihood:                -375.15
No. Observations:                 343   AIC:                             768.3
Df Residuals:                     334   BIC:                             802.8
Df Model:                           8
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     10.6182      0.418     25.425      0.000       9.797      11.440
OBP            2.7204      1.805      1.507      0.133      -0.831       6.272
SLG            2.6730      0.758      3.526      0.000       1.182       4.164
AVG           -2.8663      1.950     -1.470      0.143      -6.702       0.970
PA             0.0029      0.000     11.163      0.000       0.002       0.003
Arb            1.2810      0.108     11.842      0.000       1.068       1.494
Free           1.8326      0.101     18.155      0.000       1.634       2.031
Catch          0.1671      0.124      1.349      0.178      -0.077       0.411
Infld          0.0084      0.093      0.091      0.928      -0.174       0.191
==============================================================================
Omnibus:                        6.051   Durbin-Watson:                   1.975
Prob(Omnibus):                  0.049   Jarque-Bera (JB):                7.544
Skew:                          -0.151   Prob(JB):                       0.0230
Kurtosis:                       3.661   Cond. No.                     2.89e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.89e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [73]:
from statsmodels.iolib.summary2 import summary_col
Header = list(years[:4])
regressor_list = ['OBP','SLG','PA','AVG','Arb','Free','Catch','Infld','Intercept']
Table_Pre = summary_col(regression_list[:4],
                         regressor_order=regression_list, 
                         stars=True,
                         float_format="'%.3f'",
                         model_names = Header)
print(Table_Pre)

==============================================================
                   1999        2001        2000        2002
--------------------------------------------------------------
Intercept      '10.545'*** '10.195'*** '10.002'*** '10.333'***
               ('0.320')   ('0.342')   ('0.362')   ('0.406')
OBP            '0.755'     '0.683'     '2.986'**   '0.731'
               ('1.392')   ('1.461')   ('1.463')   ('1.827')
SLG            '3.421'***  '3.395'***  '2.819'***  '2.347'***
               ('0.602')   ('0.649')   ('0.667')   ('0.763')
AVG            '-3.036'*   '-1.336'    '-1.840'    '-0.306'
               ('1.771')   ('1.983')   ('1.851')   ('2.110')
PA             '0.003'***  '0.003'***  '0.002'***  '0.003'***
               ('0.000')   ('0.000')   ('0.000')   ('0.000')
Arb            '1.197'***  '1.116'***  '1.296'***  '1.289'***
               ('0.088')   ('0.100')   ('0.102')   ('0.115')
Free           '1.626'***  '1.786'***  '1.909'***  '1.935'***
               ('0.088')   ('0.097')   ('0.099')   ('0.119')
Catch          '0.022'     '0.167'     '0.048'     '0.075'
               ('0.102')   ('0.114')   ('0.121')   ('0.126')
Infld          '0.075'     '0.095'     '-0.008'    '-0.070'
               ('0.076')   ('0.082')   ('0.085')   ('0.094')
R-squared      '0.749'     '0.735'     '0.699'     '0.664'
R-squared Adj. '0.743'     '0.729'     '0.692'     '0.657'
==============================================================
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01

In [74]:
Header = list(years[4:])
regressor_list = ['OBP','SLG','PA','AVG','Arb','Free','Catch','Infld','Intercept']
Table_MB = summary_col(regression_list[4:],
                         regressor_order=regression_list, 
                         stars=True,
                         float_format="'%.3f'",
                         model_names = Header)
print(Table_MB)

=========================================================================
                   2003        2004       2005        2006        2007
-------------------------------------------------------------------------
Intercept      '10.293'*** '10.173'*** '9.898'*** '10.069'*** '10.618'***
               ('0.430')   ('0.458')   ('0.448')  ('0.468')   ('0.418')
OBP            '3.012'*    '7.559'***  '4.760'**  '3.421'*    '2.720'
               ('1.819')   ('1.852')   ('1.918')  ('1.863')   ('1.805')
SLG            '2.197'**   '3.056'***  '3.768'*** '2.118'***  '2.673'***
               ('0.869')   ('0.847')   ('0.817')  ('0.811')   ('0.758')
AVG            '-2.741'    '-8.064'*** '-4.350'*  '-1.448'    '-2.866'
               ('2.190')   ('2.328')   ('2.269')  ('2.350')   ('1.950')
PA             '0.003'***  '0.003'***  '0.003'*** '0.003'***  '0.003'***
               ('0.000')   ('0.000')   ('0.000')  ('0.000')   ('0.000')
Arb            '1.238'***  '1.019'***  '1.101'*** '1.199'***  '1.281'***
               ('0.114')   ('0.118')   ('0.120')  ('0.117')   ('0.108')
Free           '1.811'***  '1.523'***  '1.744'*** '1.794'***  '1.833'***
               ('0.115')   ('0.115')   ('0.118')  ('0.109')   ('0.101')
Catch          '0.282'**   '0.086'     '0.088'    '0.142'     '0.167'
               ('0.133')   ('0.136')   ('0.137')  ('0.131')   ('0.124')
Infld          '-0.060'    '-0.067'    '-0.051'   '0.034'     '0.008'
               ('0.096')   ('0.101')   ('0.098')  ('0.094')   ('0.093')
R-squared      '0.656'     '0.615'     '0.631'    '0.645'     '0.654'
R-squared Adj. '0.647'     '0.606'     '0.622'    '0.636'     '0.646'
=========================================================================
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01